# Generated by Django 5.2.15 on 2026-08-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_cb_mst_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbmenu',
            options={'ordering': ['group_order', 'menu_order']},
        ),
        migrations.AlterField(
            model_name='cbmenu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CbAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(max_length=50)),
                ('action', models.CharField(db_index=True, max_length=24)),
                ('entity', models.CharField(db_index=True, max_length=60)),
                ('entity_label', models.CharField(blank=True, max_length=80)),
                ('record_id', models.CharField(blank=True, max_length=40)),
                ('record_label', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'cb_audit_log',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['entity', 'ts'], name='cb_audit_lo_entity_2a9135_idx'), models.Index(fields=['user_id', 'ts'], name='cb_audit_lo_user_id_a0271b_idx'), models.Index(fields=['action', 'ts'], name='cb_audit_lo_action_c1c0cc_idx')],
            },
        ),
    ]
