# Generated by Django 5.2.15 on 2026-08-19 06:21

import chatbot.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_cbmenu_options_alter_cbmenu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbauditlog',
            name='changes',
            field=chatbot.fields.PortableJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sources',
            field=chatbot.fields.PortableJSONField(blank=True, default=list),
        ),
    ]
